import test from 'node:test';
import assert from 'node:assert/strict';
import {Vector3} from '../dist/vendor/three.module.js';
import {Helicopter, STEP,DEFAULTS,ORIGINAL_DEFAULTS} from '../dist/physics.js';
const clean={groundEffect:0,translationalLift:0,weathercock:0,rotorDiscDrag:0,forwardDrag:1,collectiveMode:'hold',angularInertia:1,lateralDrag:1,yawSpeedScale:32};
function airborne(config={}){const h=new Helicopter({...clean,...config});h.reset({position:[0,100,0],collective:.5});return h;}
function run(h,seconds,input={}){for(let i=0;i<Math.round(seconds/STEP);i++)h.step(input,STEP);return h;}
test('neutral thrust balances gravity away from the ground',()=>{const h=run(airborne(),10);assert.ok(Math.abs(h.position.y-100)<1e-8);assert.ok(h.velocity.length()<1e-8);});
test('right roll banks right and accelerates right; pitch-up tilts the nose up',()=>{const roll=run(airborne(),.5,{roll:1});assert.ok(roll.telemetry().roll>0);assert.ok(roll.up.x>0);assert.ok(roll.velocity.x>0);const pitch=run(airborne(),.5,{pitch:1});assert.ok(pitch.telemetry().pitch>0);assert.ok(pitch.velocity.z>0);});
test('yaw right increases heading without banking or rotating velocity instantly',()=>{const h=airborne();h.velocity.set(0,0,-20);run(h,.5,{yaw:1});assert.ok(h.telemetry().heading>0&&h.telemetry().heading<90);assert.ok(Math.abs(h.telemetry().roll)<1e-8);assert.ok(Math.abs(h.velocity.x)<.05);assert.ok(h.velocity.z<-18);});
test('banked lift loses altitude instead of automatically compensating',()=>{const h=airborne();h.orientation.setFromAxisAngle(new Vector3(0,0,1),-Math.PI/3);run(h,1);assert.ok(h.velocity.y<-4);assert.ok(h.velocity.x>7);});
test('released cyclic damps angular rate while keeping bank',()=>{const h=run(airborne(),.5,{roll:1});const rate=Math.abs(h.rates.z);run(h,2);assert.ok(Math.abs(h.rates.z)<rate*.08);assert.ok(h.telemetry().roll>15);});
test('yaw authority weakens with forward speed',()=>{const hover=run(airborne(),.5,{yaw:1});const fast=airborne();fast.velocity.z=-50;run(fast,.5,{yaw:1});assert.ok(Math.abs(fast.rates.y)<Math.abs(hover.rates.y)*.5);});
test('collective can hold position or return to neutral, with thrust lag',()=>{const hold=run(airborne(),.3,{collective:1});const value=hold.collective;assert.ok(hold.rotor<value);run(hold,.3);assert.equal(hold.collective,value);const spring=run(airborne({collectiveMode:'spring'}),.3,{collective:1});run(spring,2);assert.ok(Math.abs(spring.collective-spring.config.neutral)<.001);});
test('quaternions stay normalized through full rolls and inverted flight',()=>{const h=airborne({rollPower:6,angularDamping:.8});h.position.y=1000;run(h,7,{roll:1});assert.ok(Math.abs(h.orientation.length()-1)<1e-10);assert.ok(Number.isFinite(h.position.length()));assert.equal(h.crashed,false);});
test('safe touchdown records sink and hard touchdown crashes',()=>{const safe=airborne();safe.position.y=1;safe.velocity.y=-.8;safe.collective=safe.rotor=.1;run(safe,.15);assert.equal(safe.crashed,false);assert.equal(safe.onGround,true);assert.ok(safe.lastLanding.sink<1.5);const hard=airborne();hard.position.y=1;hard.velocity.y=-6;run(hard,.025);assert.equal(hard.crashed,true);assert.equal(hard.impact.reason,'Hard landing');});
test('fixed-step results are identical at 30, 60 and 144 render fps',()=>{const simulate=fps=>{const h=airborne();let acc=0;for(let frame=0;frame<fps*2;frame++){acc+=1/fps;while(acc+1e-12>=STEP){h.step({pitch:-.2,roll:.1,yaw:.2},STEP);acc-=STEP;}}return h;};const reference=simulate(30);for(const fps of [60,144]){const h=simulate(fps);assert.ok(h.position.distanceTo(reference.position)<1e-9);assert.ok(h.orientation.angleTo(reference.orientation)<1e-7);}});
test('obstacles stop flight with a named impact',()=>{const h=airborne();h.step({},STEP,()=>0,[{x:0,z:0,hx:5,hz:5,bottom:0,top:110}]);assert.equal(h.crashed,true);assert.equal(h.impact.reason,'Obstacle strike');});
test('trees allow brushing outer branches and tips while retaining core and trunk collisions',()=>{
  const tree={type:'tree',x:0,z:0,base:100,bottom:105.2,top:118,radius:2.6,trunkTop:106.4,trunkRadius:.14};
  for(const [x,y,hit]of [[3,107,false],[1,114,false],[0,119,false],[.3,103,false],[.5,107,true],[0,103,true]]){
    const heli=airborne();heli.position.set(x,y,0);heli.step({},STEP,()=>0,[tree]);assert.equal(heli.crashed,hit,`tree pass at ${x},${y}`);
  }
});
test('optional leveling assist restores bank rather than amplifying it',()=>{const h=airborne({stability:2});h.orientation.setFromAxisAngle(new Vector3(0,0,1),-.3);run(h,1);assert.ok(Math.abs(h.telemetry().roll)<10);assert.ok(h.rates.z>0);});
test('weighted inertia ramps more slowly but retains the same eventual turn authority',()=>{const light=run(airborne({angularInertia:ORIGINAL_DEFAULTS.angularInertia}),.5,{roll:1});const heavy=run(airborne({angularInertia:DEFAULTS.angularInertia}),.5,{roll:1});assert.ok(Math.abs(heavy.rates.z)<Math.abs(light.rates.z)*.75);light.position.y=heavy.position.y=1000;run(light,5,{roll:1});run(heavy,5,{roll:1});assert.ok(Math.abs(heavy.rates.z/light.rates.z-1)<.02);});
test('weighted inertia demands earlier counter-input and keeps more angular momentum',()=>{const light=run(airborne({angularInertia:1}),.5,{roll:1});const heavy=run(airborne({angularInertia:1.65}),.5,{roll:1});const lightRate=Math.abs(light.rates.z),heavyRate=Math.abs(heavy.rates.z);run(light,1);run(heavy,1);assert.ok(Math.abs(heavy.rates.z)/heavyRate>Math.abs(light.rates.z)/lightRate*1.7);});
test('weighted drag retains sideways momentum after the nose changes direction',()=>{const light=airborne({lateralDrag:1}),heavy=airborne({lateralDrag:.45});light.velocity.x=heavy.velocity.x=30;run(light,3);run(heavy,3);assert.ok(heavy.velocity.x>light.velocity.x*1.5);assert.ok(heavy.position.x>light.position.x*1.25);});
